export const springfieldAgents = [
  {
    id: "apu",
    name: "Apu",
    initials: "AP",
    color: "#26A69A",
    archetype: "disciplined probability trader",
    edge: "best no-trade discipline and process consistency",
    weakness: "can miss explosive moves by being too selective",
    preferredRegimes: ["trend", "range"],
    avoidRegimes: ["chaos"],
    strategyNames: ["VWAP Reclaim", "Trend Pullback", "Volume Surge"],
    role: "trader",
  },
  {
    id: "bart",
    name: "Bart",
    initials: "BA",
    color: "#FF6D01",
    archetype: "breakout gunner",
    edge: "fast momentum and breakout participation",
    weakness: "can chase too hard into traps",
    preferredRegimes: ["breakout", "trend"],
    avoidRegimes: ["range"],
    strategyNames: ["Momentum Break", "Volume Surge", "Liquidity Sweep Reversal"],
    role: "trader",
  },
  {
    id: "marge",
    name: "Marge",
    initials: "MA",
    color: "#4285F4",
    archetype: "capital preserver",
    edge: "safe entries and strong filtering",
    weakness: "under-trades when opportunity is obvious",
    preferredRegimes: ["trend", "range"],
    avoidRegimes: ["chaos"],
    strategyNames: ["VWAP Reclaim", "Trend Pullback", "Volume Surge"],
    role: "trader",
  },
  {
    id: "maggie",
    name: "Maggie",
    initials: "MG",
    color: "#00ACC1",
    archetype: "silent sniper",
    edge: "range and snapback precision",
    weakness: "low sample size because she waits a lot",
    preferredRegimes: ["range"],
    avoidRegimes: ["breakout", "chaos"],
    strategyNames: ["Range Fade", "VWAP Reclaim", "RSI Reversal"],
    role: "trader",
  },
  {
    id: "nelson",
    name: "Nelson",
    initials: "NE",
    color: "#EF5350",
    archetype: "aggressive downside hunter",
    edge: "best at sharp downside continuation and trap reversals",
    weakness: "forces shorts in weak contexts",
    preferredRegimes: ["breakout", "chaos"],
    avoidRegimes: ["range"],
    strategyNames: ["Liquidity Sweep Reversal", "Momentum Break", "RSI Reversal"],
    role: "trader",
  },
  {
    id: "lisa",
    name: "Lisa",
    initials: "LI",
    color: "#FBC02D",
    archetype: "strategy mentor",
    edge: "audits weak logic and raises quality standards",
    weakness: "can become too strict and reduce participation",
    preferredRegimes: ["trend", "range", "breakout"],
    avoidRegimes: ["chaos"],
    strategyNames: ["Volume Surge", "VWAP Reclaim", "Trend Pullback"],
    role: "strategist",
  },
  {
    id: "mr-burns",
    name: "Mr Burns",
    initials: "MB",
    color: "#A142F4",
    archetype: "capital allocator",
    edge: "cuts weak performers and rewards stronger systems",
    weakness: "can become too conservative after losses",
    preferredRegimes: ["trend", "breakout"],
    avoidRegimes: ["range"],
    strategyNames: ["Trend Ride", "Trend Pullback", "Volume Surge"],
    role: "strategist",
  },
  {
    id: "milhouse",
    name: "Milhouse",
    initials: "MI",
    color: "#7CB342",
    archetype: "data analyst",
    edge: "tracks what is actually working and flags weak strategy drift",
    weakness: "can become timid after a few failures",
    preferredRegimes: ["trend"],
    avoidRegimes: ["chaos"],
    strategyNames: ["Trend Pullback", "VWAP Reclaim", "RSI Reversal"],
    role: "strategist",
  },
  {
    id: "moe",
    name: "Moe",
    initials: "MO",
    color: "#8D6E63",
    archetype: "market structure coach",
    edge: "spots when mean reversion logic is being misused",
    weakness: "too contrarian if unchecked",
    preferredRegimes: ["range", "chaos"],
    avoidRegimes: ["breakout"],
    strategyNames: ["RSI Reversal", "Range Fade", "VWAP Reclaim"],
    role: "strategist",
  },
  {
    id: "comic-book-guy",
    name: "Comic Book Guy",
    initials: "CB",
    color: "#AB47BC",
    archetype: "post-trade reviewer",
    edge: "good regime classifier and detailed critic",
    weakness: "analysis paralysis",
    preferredRegimes: ["trend", "range", "breakout"],
    avoidRegimes: ["chaos"],
    strategyNames: ["VWAP Reclaim", "Trend Ride", "Momentum Break"],
    role: "strategist",
  },
] as const;
