export const strategyCatalog = [
  {
    id: "volume-surge",
    name: "Volume Surge",
    score: 84,
    report: "Strong when volume expands with clean directional follow-through.",
    when: "Use when volume spikes above recent baseline with strong candle close.",
    weakness: "Can be trapped by fake spikes.",
    improve: "Add higher timeframe trend filter.",
    versions: [
      { version: "v1.0", title: "Baseline momentum read", change: "Started as a simple volume breakout trigger.", learned: "Raw spikes alone were too noisy.", status: "archived" },
      { version: "v1.1", title: "Confirmation filter added", change: "Required stronger candle close and cleaner participation.", learned: "Volume needs structure, not just size.", status: "stable" },
      { version: "v1.2", title: "Trend alignment patch", change: "Biases trades toward higher timeframe direction.", learned: "Blind momentum gets punished in choppy reversals.", status: "active" },
    ],
  },
  {
    id: "rsi-reversal",
    name: "RSI Reversal",
    score: 74,
    report: "Useful for snapback entries after overstretched moves.",
    when: "Use when price stretches too far and RSI hits extremes.",
    weakness: "Gets punished in hard trends.",
    improve: "Pair with support and resistance.",
    versions: [
      { version: "v1.0", title: "Simple oversold/overbought fade", change: "Pure RSI extreme reversal entries.", learned: "Trend markets steamroll early fades.", status: "archived" },
      { version: "v1.1", title: "Structure-aware reversal", change: "Needs RSI extreme plus support/resistance context.", learned: "Context matters more than the oscillator alone.", status: "active" },
    ],
  },
  {
    id: "momentum-break",
    name: "Momentum Break",
    score: 81,
    report: "Best for fast breakout continuation when range compression breaks.",
    when: "Use when price breaks a tight range with conviction.",
    weakness: "False breakouts are common.",
    improve: "Require retest confirmation.",
    versions: [
      { version: "v1.0", title: "Compression break detector", change: "Trades first clean range expansion.", learned: "Low-volume breaks are unreliable.", status: "stable" },
      { version: "v1.1", title: "Retest preference", change: "Prefers break + hold instead of first poke.", learned: "Patience improved win quality.", status: "active" },
    ],
  },
  {
    id: "trend-ride",
    name: "Trend Ride",
    score: 72,
    report: "Good when the market is already trending cleanly.",
    when: "Use when the market is moving in one direction with structure.",
    weakness: "Late entries can be punished.",
    improve: "Use trailing stops and pullback entries.",
    versions: [
      { version: "v1.0", title: "Follow the tape", change: "Simple continuation logic inside trend structure.", learned: "Late continuation gets trapped near exhaustion.", status: "stable" },
      { version: "v1.1", title: "Pullback-sensitive trend ride", change: "Softens entries when move is extended.", learned: "Trend continuation works better after reset, not chase.", status: "active" },
    ],
  },
  {
    id: "vwap-reclaim",
    name: "VWAP Reclaim",
    score: 78,
    report: "Reliable intraday structure setup around fair value.",
    when: "Use when price reclaims VWAP with supporting volume.",
    weakness: "Weak in flat sessions.",
    improve: "Filter low participation periods.",
    versions: [
      { version: "v1.0", title: "Fair value reclaim", change: "Trades re-entry over VWAP after rejection.", learned: "Flat sessions create fake reclaims.", status: "stable" },
      { version: "v1.1", title: "Participation filter", change: "De-emphasizes low-energy market periods.", learned: "VWAP only matters when traders care.", status: "active" },
    ],
  },
  {
    id: "range-fade",
    name: "Range Fade",
    score: 69,
    report: "Solid in sideways conditions, weak in expansion.",
    when: "Use when price repeatedly rejects the same boundaries.",
    weakness: "Breakouts kill it.",
    improve: "Disable in volatility expansion.",
    versions: [
      { version: "v1.0", title: "Range edge fade", change: "Fades repeated top and bottom rejections.", learned: "Breakout regimes destroy naive range fades.", status: "active" },
    ],
  },
  {
    id: "trend-pullback",
    name: "Trend Pullback",
    score: 76,
    report: "Cleaner entries inside healthy trends.",
    when: "Use when price pulls back into a strong trend.",
    weakness: "Fails when trend is exhausted.",
    improve: "Use moving average and structure alignment.",
    versions: [
      { version: "v1.0", title: "Pullback continuation", change: "Joins trend on retracement into support/resistance zone.", learned: "Best entries come from clean structure, not shallow noise.", status: "active" },
    ],
  },
  {
    id: "liquidity-sweep-reversal",
    name: "Liquidity Sweep Reversal",
    score: 71,
    report: "Can catch high RR reversals after stop hunts.",
    when: "Use when price sweeps highs or lows then snaps back.",
    weakness: "Hard to time cleanly.",
    improve: "Wait for reclaim confirmation.",
    versions: [
      { version: "v1.0", title: "Sweep and snapback", change: "Looks for stop hunt then quick reversal.", learned: "Needs confirmation or it becomes knife-catching.", status: "stable" },
      { version: "v1.1", title: "Reclaim confirmation", change: "Requires price to reclaim the level after sweep.", learned: "Confirmation reduced early failures.", status: "active" },
    ],
  },
  {
    id: "micro-breakout-scalp",
    name: "Micro Breakout Scalp",
    score: 73,
    report: "Scalps tiny intraday range expansions when price compresses tightly.",
    when: "Use when short-term range is tight and momentum starts to expand.",
    weakness: "Chop can fake out the first break.",
    improve: "Require micro retest and volume confirmation.",
    versions: [{ version: "v1.0", title: "Fast breakout scalp", change: "Short-window breakout entry.", learned: "Needs cleaner confirmation to avoid noise.", status: "active" }],
  },
  {
    id: "orderflow-flip-scalp",
    name: "Orderflow Flip Scalp",
    score: 74,
    report: "Targets fast reversals when short-term orderflow bias flips.",
    when: "Use when aggressive pressure exhausts and immediate reversal starts.",
    weakness: "Very sensitive to false flips.",
    improve: "Add stronger exhaustion filter.",
    versions: [{ version: "v1.0", title: "Pressure flip", change: "Scalps abrupt pressure reversals.", learned: "Exhaustion matters more than speed alone.", status: "active" }],
  },
  {
    id: "ema-ribbon-scalp",
    name: "EMA Ribbon Scalp",
    score: 75,
    report: "Uses fast EMA stack alignment for quick continuation entries.",
    when: "Use when short EMAs align cleanly and price respects them.",
    weakness: "Late entries get punished after extension.",
    improve: "Only enter after micro pullback.",
    versions: [{ version: "v1.0", title: "Fast EMA follow", change: "Scalps with short-term moving-average structure.", learned: "Needs better extension control.", status: "active" }],
  },
  {
    id: "wick-rejection-scalp",
    name: "Wick Rejection Scalp",
    score: 72,
    report: "Scalps immediate reversals after sharp wick rejection.",
    when: "Use when price rejects a level violently and snaps back.",
    weakness: "Weak if rejection comes without follow-through.",
    improve: "Add close confirmation after wick event.",
    versions: [{ version: "v1.0", title: "Rejection snapback", change: "Takes fast wick rejection reversals.", learned: "Reclaim confirmation improves survival.", status: "active" }],
  },
  {
    id: "opening-range-scalp",
    name: "Opening Range Scalp",
    score: 76,
    report: "Scalps the first clean break of a short opening range.",
    when: "Use when initial balance forms clearly and breaks with momentum.",
    weakness: "Flat opens make it useless.",
    improve: "Avoid weak participation windows.",
    versions: [{ version: "v1.0", title: "Opening range push", change: "First break of short range gets traded.", learned: "Volume context matters more than the box itself.", status: "active" }],
  },
  {
    id: "pullback-bounce-scalp",
    name: "Pullback Bounce Scalp",
    score: 77,
    report: "Quick continuation scalp after controlled pullback.",
    when: "Use when trend remains intact and pullback is shallow and orderly.",
    weakness: "Fails when pullback is actually reversal.",
    improve: "Tie to higher timeframe trend bias.",
    versions: [{ version: "v1.0", title: "Shallow reset continuation", change: "Joins trend after a quick reset.", learned: "Shallow pullback quality matters a lot.", status: "active" }],
  },
  {
    id: "liquidity-grab-scalp",
    name: "Liquidity Grab Scalp",
    score: 74,
    report: "Scalps after a small stop-run and immediate reclaim.",
    when: "Use when local liquidity gets grabbed and price reclaims fast.",
    weakness: "Can knife-catch if reclaim is weak.",
    improve: "Wait for reclaim candle close.",
    versions: [{ version: "v1.0", title: "Mini stop-run fade", change: "Targets short-term liquidity grabs.", learned: "Reclaim quality is the whole trade.", status: "active" }],
  },
  {
    id: "vwap-bounce-scalp",
    name: "VWAP Bounce Scalp",
    score: 78,
    report: "Scalps fast mean reversion or continuation around VWAP touch.",
    when: "Use when price tags VWAP and reacts decisively.",
    weakness: "Weak if VWAP is flat and ignored.",
    improve: "Combine with participation filter.",
    versions: [{ version: "v1.0", title: "VWAP touch reaction", change: "Scalps direct response at VWAP.", learned: "Needs active session participation.", status: "active" }],
  },
  {
    id: "rsi-micro-scalp",
    name: "RSI Micro Scalp",
    score: 70,
    report: "Short-horizon RSI snapback scalp.",
    when: "Use when micro RSI hits an extreme with price stretch.",
    weakness: "Very weak in directional flow.",
    improve: "Gate it harder in trends.",
    versions: [{ version: "v1.0", title: "Micro oscillator fade", change: "Scalps quick RSI extremes.", learned: "Trend filter is mandatory.", status: "active" }],
  },
  {
    id: "channel-break-scalp",
    name: "Channel Break Scalp",
    score: 75,
    report: "Scalps channel edge breaks when compression resolves.",
    when: "Use when price compresses inside a clean micro channel.",
    weakness: "Noisy channels create false entries.",
    improve: "Require cleaner channel quality score.",
    versions: [{ version: "v1.0", title: "Micro channel release", change: "Trades channel resolution.", learned: "Structure clarity matters more than frequency.", status: "active" }],
  },
] as const

export const strategyCatalogByName = Object.fromEntries(strategyCatalog.map((strategy) => [strategy.name, strategy]))
export const strategyCatalogById = Object.fromEntries(strategyCatalog.map((strategy) => [strategy.id, strategy]))
